AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC for when GitHub wants to communicate with AWS.
Parameters:
  RepositoryName:
    Type: String
    Description: The name of the GitHub repository
    Default: 'muneebbukhari555/*'
  BucketName:
    Description: S3 Bucket for terraform remote state storage
    Default: "demo-state-bucket"
    Type: String
    
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_Infra_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${RepositoryName}' #['repo:muneebbukhari555/*']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  
  # This is the OIDC provider hookup itself. This tells AWS to delegate authN GitHub
  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Url: https://token.actions.githubusercontent.com

  # S3 Bucket for terraform remote state storage
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Role:
    Value: !GetAtt Role.Arn
